services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: django-backend
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - db-data:/app/data


  frontend:
    build: ./frontend
    container_name: react-frontend
    stdin_open: true
    ports:
      - "5173:5173"
    expose:
      - "5173"
    depends_on:
      - backend
    networks:
      - app-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-network

networks:
  app-network:
    # driver: bridge

volumes:
  db-data: