version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: django-backend
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    stdin_open: true
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network
    command: >
      sh -c "npm install && npm run build && npx serve -s build -l 80"

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-network

networks:
  app-network:
    # driver: bridge