version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: django-backend
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend  # match the name used in Nginx
    stdin_open: true
    expose:
      - "80"  # use expose instead of ports; Nginx will access it internally
    depends_on:
      - backend
    command: >
      sh -c "npm install && npm run build && npx serve -s build -l 80"

nginx:
  image: nginx:alpine
  container_name: nginx-proxy
  ports:
    - "80:80"
  volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - frontend
    - backend

networks:
  app-network:
