# Generated by Django 5.1.7 on 2025-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='appointmentdomicile',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentdomicile',
            name='car_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentdomicile',
            name='place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentdomicile',
            name='wash_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentlocation',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentlocation',
            name='car_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentlocation',
            name='wash_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='externemployee',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='internemployee',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
