# Generated by Django 5.1.6 on 2025-03-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0003_externemployeehistory_internemployeehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
