# Generated by Django 5.1.6 on 2025-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0005_internemployee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdomicile',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
