# Generated by Django 5.1.6 on 2025-04-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0010_remove_appointmentdomicile_date'),
    ]

    operations = [

    ]
