name: Deploy to VPS (Docker + Nginx) (django backend, React frontend)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Copy files to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
            mkdir -p ~/app
          "
          rsync -avz --exclude='.git' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:~/app

      - name: Run Docker Compose on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
            cd ~/app &&
            docker compose down &&
            docker compose up --build -d
          "
